apps/shop/urls.py
from django.urls import path

from .views import (AddCompareView, AddFavoritesView, AddWaitingFavoritesView,
                    AvailableView, CalculateShippingView, CartAddView,
                    CartDeleteView, CartTemplate, CartUpdateView, CompareView,
                    DeleteCompareView, DeleteFavoritesView, FavoritesView,
                    OrderCreate, OrderView, PaymentRedirectView,
                    RestoreCompareView, RestoreFavoritesView)

urlpatterns = [
    path('shop/cart/', CartTemplate.as_view(), name='cart'),
    path('shop/order/', OrderView.as_view(), name='order'),
    path('shop/favorites/', FavoritesView.as_view(), name='favorites'),
    path('shop/compare/', CompareView.as_view(), name='compare'),
    path('shop/validate-payment/',
         PaymentRedirectView.as_view(), name='validate-payment'),

    # Ajax обработчики

    path('api/shop/cart/available/', AvailableView.as_view(), name='available'),
    path('api/shop/order/calculate/',
         CalculateShippingView.as_view(), name='calculate-shipping'),
    path('api/shop/cart/add/', CartAddView.as_view(), name='cart-add'),
    path('api/shop/cart/update/', CartUpdateView.as_view(),
         name='cart-update'),
    path('api/shop/cart/delete/', CartDeleteView.as_view(),
         name='cart-delete'),
    path('api/shop/order/create/', OrderCreate.as_view(),
         name='order-create'),
    path('api/shop/favorites/add', AddFavoritesView.as_view(),
         name='favorites-add'),
    path('api/shop/favorites/delete', DeleteFavoritesView.as_view(),
         name='favorites-delete'),
    path('api/shop/favorites/restore', RestoreFavoritesView.as_view(),
         name='favorites-restore'),
    path('api/shop/favorites/add-waiting',
         AddWaitingFavoritesView.as_view(),
         name='favorites-add-waiting'),
    path('api/shop/compare/add', AddCompareView.as_view(),
         name='compare-add'),
    path('api/shop/compare/delete', DeleteCompareView.as_view(),
         name='compare-delete'),
    path('api/shop/compare/restore', RestoreCompareView.as_view(),
         name='compare-restore'),
]

system/urls.py
from apps.catalog.models import CategorySitemap, ProductSitemap
from apps.pages.views import return_js
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
#
from django.urls import include, path, reverse
#  delete later
from django.views.generic import RedirectView, TemplateView


class StaticViewSitemap(Sitemap):
    priority = 0.5
    changefreq = 'daily'

    def items(self):
        return ['catalog', ]

    def location(self, item):
        return reverse(item)


sitemaps = {
    'products': ProductSitemap,
    'categorys': CategorySitemap,
    # 'posts': SitemapCatPage,
    # 'catsposts': SitemapPost,
    # 'pages': SitemapPage,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('favicon.ico',
         RedirectView.as_view(url='/static/images/favicon.png'),
         name='favicon'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    path('admin/', admin.site.urls),

    # Прочие приложения
    path('filer/', include('filer.urls')),
    path('ajax_lookup/', include('ajax_select.urls'),
         name='ajax_lookup'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # delete later
    path('dev_page', TemplateView.as_view(
        template_name="dev_page.html"), name='dev_page'),
    path('dev_text_page', TemplateView.as_view(
        template_name="dev_text_page.html"), name='dev_page'),
    # path('404', not_found_view),

    path('sw.js', return_js),

    # Основные приложения
    path('', include('apps.seo.urls')),
    path('', include('apps.feedback.urls')),
    path('', include('apps.exchange1c.urls')),
    path('', include('apps.catalog.urls')),
    path('', include('apps.account.urls')),
    path('', include('apps.shop.urls')),
    path('', include('apps.pages.urls')),
    path('', include('apps.posts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/shop/models/compare.py
from apps.account.models import Account
from apps.catalog.models import Product
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Compare(models.Model):
    """Модель сравнения товаров"""

    account = models.OneToOneField(
        Account, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.account.user.username

    def items(self):
        return self.compare_items.all()

    def count(self):
        return len(self.items())

    class Meta:
        verbose_name = "избранные товары"
        verbose_name_plural = "Избранные товары"


class CompareItem(models.Model):
    """Модель элементов избранных товаров"""

    compare = models.ForeignKey(
        Compare, related_name="compare_items", on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name="product_compare_items", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "элемент товаров для сравнения"
        verbose_name_plural = "Элементы товаров для сравнения"


@receiver(post_save, sender=Account)
def create_compare(sender, instance, created, **kwargs):
    """Создание новой модели избранных товаров пользователя личного кабинета.

    Модель избранных товаров создается по сигналу сохраненного пользователя
    личного кабинета, и привязывается к созданному пользователю. Модель
    избранных товаров создается только в том случае если пользователь был
    создан, а не просто сохранен.

    Arguments:
        sender {Account} -- Модель пользователя личного кабинета
        instance {Compare} -- Экземпляр пользователя личного кабинета
        created {bool} -- Показывает был ли создан профиль пользователя
    """

    if created:
        Compare.objects.create(account=instance)


@receiver(post_save, sender=Account)
def save_compare(sender, instance, **kwargs):
    """Сохранение модели уже существующей корзины пользователя личного кабинета.

    Корзина сохраняется по сигнялу сохранения пользователя личного кабинета.

    Arguments:
        sender {Account} -- Модель пользователя личного кабинета
        instance {Compare} -- Экземпляр пользователя личного кабинета
    """

    instance.compare.save()


class UnauthCompare:
    """Избранные товары неавторизованного пользователя"""

    def __init__(self, compare_items=list()):
        self.compare_items = compare_items

    def items(self):
        return self.compare_items

    def count(self):
        return len(self.compare_items)


class UnauthCompareItem:
    """Элемент избранных товаров неавторизованного пользователя."""

    def __init__(self, product=None):
        self.product = product

apps/shop/models/order.py
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.query_utils import Q
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.timezone import datetime
from filer.fields.image import FilerFileField

from apps.account.models import Account
from apps.catalog.models import Color, Option, Product

from .order_state import OrderState


class Order(models.Model):
    """
    Модель заказа товаров
    """

    # Стадии заказа
    STATUSES = (
        ("processing", "В обработке"),
        ("completed", "Выполнен"),
        ("canceled", "Отменен"),
        ("stash", "Сохранен"),
    )

    SHIPPINGS = (
        ("self", "Самовывоз"),
        ("transport", "Транспотной компанией"),
        ("post", "Почтой"),
        ("courier", "Курьером"),
        ("dostavka", "Доставка"),
    )

    PAYMENTS = (
        ("bank", "Банковской картой онлайн"),
        ("bill", "Оплата по счету"),
        ("receiving", "Оплата при получении"),
    )

    UPLOAD = (
        ("doNotUpload", "Не подлежит выгрузке"),
        ("not_upload", "Не выгружен"),
        ("upload", "Выгружен"),
        ("processing", "В процессе"),
    )

    account = models.ForeignKey(
        Account,
        verbose_name="Профиль",
        blank=True,
        null=True,
        related_name="orders",
        on_delete=models.SET_NULL,
    )
    surname = models.CharField(
        verbose_name="Фамилия", default="", blank=True, max_length=100
    )
    name = models.CharField(verbose_name="Имя", default="", blank=True, max_length=300)
    middle_name = models.CharField(
        verbose_name="Отчество", default="", blank=True, max_length=300
    )
    phone = models.CharField(
        verbose_name="Телефон", default="", blank=True, max_length=300
    )
    email = models.EmailField(verbose_name="Email", default="", blank=False)
    comment = models.TextField(verbose_name="Комментарий", blank=True, max_length=300)
    date = models.DateTimeField(verbose_name="Дата заказа", default=datetime.now)
    total = models.FloatField(
        verbose_name="Общая стоимость заказа", null=True, blank=True
    )
    bank_id = models.CharField(
        verbose_name="Ид заказа в системе банка", default="", blank=True, max_length=100
    )
    payment = models.BooleanField(verbose_name="Заказ оплачен", default=False)
    status = models.CharField(
        verbose_name="Статус", choices=STATUSES, default="processing", max_length=50
    )
    type_payment = models.CharField(
        verbose_name="Способ оплаты",
        choices=PAYMENTS,
        default="receiving",
        max_length=50,
    )
    shipping = models.CharField(
        verbose_name="Доставка", choices=SHIPPINGS, default="self", max_length=50
    )
    shipping_price = models.FloatField(verbose_name="Стоимость доставки", default=0)
    post_code = models.PositiveIntegerField(
        verbose_name="Почтовый индекс", null=True, blank=True
    )
    region = models.CharField(
        verbose_name="Область", default="", blank=True, max_length=200
    )
    district = models.CharField(
        verbose_name="Район", default="", blank=True, max_length=200
    )
    city = models.CharField(
        verbose_name="Нас. пункт", default="", blank=True, max_length=200
    )

    street = models.CharField(
        verbose_name="Улица", default="", blank=True, max_length=200
    )
    house = models.CharField(verbose_name="Дом", default="", blank=True, max_length=200)
    housing = models.CharField(
        verbose_name="Корпус", default="", blank=True, max_length=100
    )

    apartment = models.CharField(
        verbose_name="Квартира", default="", blank=True, max_length=50
    )
    entrance = models.CharField("Подъезд", default="", blank=True, max_length=50)
    # WTF 2 comment oO
    comment = models.TextField(verbose_name="Комментарий", default="", blank=True)

    shipping_type_name = models.CharField(
        verbose_name="Способ доставки", default="", blank=True, max_length=50
    )

    status_imported = models.CharField(
        "Загружены в 1С",
        default="not_upload",
        editable=True,
        choices=UPLOAD,
        max_length=25,
    )

    shop_address = models.CharField(
        "Адрес магазина", default="", blank=True, max_length=255
    )

    company_title = models.CharField(
        "Название компании", default="", blank=True, max_length=125
    )
    company_inn = models.CharField(
        "ИНН компании", default="", blank=True, max_length=125
    )
    payment_file = models.FileField(
        "Реквизиты", default="", blank=True, upload_to="files/payment/"
    )

    jurical = models.BooleanField("Заказ от юр. лица", default=False)

    total_without_points = models.FloatField(
        verbose_name="Стоимость заказа без вычета бонусов",
        validators=[MinValueValidator(0)],
        default=0,
    )

    points_spent = models.FloatField(
        verbose_name="Количество потраченных бонусов",
        validators=[MinValueValidator(0)],
        default=0,
    )

    points_collected = models.FloatField(
        verbose_name="Количество баллов, которые пользователь получит после оплаты",
        validators=[MinValueValidator(0)],
        default=0,
    )

    is_deleted = models.BooleanField(
        verbose_name="Заказ удален?",
        default=False,
        help_text="Вместо удаления заказа отметьте этот пункт",
    )

    is_confirmed = models.BooleanField(
        verbose_name="Заказ был подтевержден",
        default=False,
        help_text=(
            "Техническое поле необходимое для"
            "обновления поля 'сумма покупок'"
            "у пользовтеля, совершившего заказ"
        ),
    )

    current_state = models.ForeignKey(
        OrderState,
        verbose_name="Текущее состояние заказа",
        on_delete=models.SET_DEFAULT,
        default=OrderState.default,
        related_name="orders",
    )

    completed_states = models.ManyToManyField(
        OrderState, verbose_name="Выполненные состояния", related_name="passed_orders"
    )

    def __str__(self):
        return "Заказ № " + str(self.id)

    def str_type_payment(self):
        return dict(Order.PAYMENTS)[self.type_payment]

    def str_shipping(self):
        return dict(Order.SHIPPINGS)[self.shipping]

    def status_value(self):
        """Получаем значение статуса заказа относительно его ключа.

        Returns:
            str -- Значение статуса заказа
        """

        return dict(self.STATUSES)[self.status]

    def get_filename(self):
        if self.payment_file:
            return self.payment_file.name.split("/")[-1]
        return ""

    def is_shipping_default(self):
        return self.shipping == "self"

    def get_shipping_address(self):
        return f"{self.region}, подъезд №{self.entrance}"

    def save_in_stash(self):
        """Пометить заказ, как сохраненный."""
        self.status = "stash"
        self.save()

    def remove_from_stash(self):
        self.status = "processing"
        self.save()

    @property
    def should_send_email(self) -> bool:
        """Проверка на то, что сообщение о создании заказа
        должно быть отправлено.

        Returns:
            bool: Результат проверки
        """
        return not self.is_in_stash and self.type_payment != "bank"

    @property
    def is_in_stash(self):
        """Проверка заказа на то, что он сохранен."""
        return self.status == "stash"

    def update_fields(self, data):
        self.district = data.get("district", "")
        self.city = data.get("city", "")
        self.street = data.get("street", "")
        self.house = data.get("house", "")
        self.housing = data.get("housing", "")
        self.apartment = data.get("apartment", "")
        self.comment = data.get("comment", "")
        self.type_payment = data.get("payment")
        self.shipping_price = data.get("calculated_shipping_price")
        self.payment_file = data.get("payment_file", None)
        self.status = "processing"
        self.shipping_type_name = data.get("shipping_title", "")
        self.shipping = data.get("shipping_code", "")
        self.region = data.get("region", "")
        self.entrance = data.get("entrance", "")
        self.status_imported = data.get("status_imported", "")
        self.jurical = data.get("jurical", False)
        self.save()

    def remove(self):
        self.is_deleted = True
        self.status_imported = "doNotUpload"
        return self

    def count_order(self):
        items = self.order_items.all()
        self.total = 0
        new_total = 0
        for item in items:
            new_total += item.total_price()
        self.total = round(new_total, 2)
        self.save()
        return self.total

    def set_date(self):
        """Обновление даты заказа."""
        self.date = datetime.now()
        self.save()

    def get_default_total(self):
        """Получить полную стоимость заказа,
        рассчитанную по дефолтной цене.

        Returns:
            float: Стоимость заказа
        """
        total_price = 0
        for item in self.order_items.all():
            item_price = item.option.price if item.option else item.product.price
            count = item.count
            total_price += round(item_price * count, 2)
        return total_price

    def add_completed_state(self, state: OrderState):
        """Добавить к заказу выполненное состояние.

        Если было передано состояние, которое уже
        находится среди выполенных состояний текущего
        заказа, то исключение поднято не будет, но
        новое состояние также не будет добавлено

        Args:
            state (OrderState): Новое состояние
        """
        assert isinstance(
            state, OrderState
        ), "Значение должно быть экземпляром класса OrderState"

        if state in self.completed_states.all():
            return
        self.completed_states.add(state)
        self.save()

    @property

apps/shop/views/payment.py
from apps.configuration.utils import BankPayment
from django.shortcuts import get_object_or_404
from django.views.generic.base import RedirectView

from ..models import Order


class PaymentRedirectView(RedirectView):
    permanent = False
    query_string = False
    pattern_name = 'account-orders'

    def get_redirect_url(self, *args, **kwargs):
        order = get_object_or_404(
            Order, bank_id=self.request.GET.get("orderId", "None"))
        payment = BankPayment(order, self.request)

        if payment.is_valid():
            payment.set_status_order()

        if not self.request.user.is_authenticated:
            self.url = "/"

        return super().get_redirect_url(*args, **kwargs)

apps/shop/templates/shop/cart.html
{% extends "base.html" %}
{% load utils %}

{% block content %}
<div class="base-page">
    <div class="container">
        <div class="breadcrumbs">
            <ul>
                <li><a href="/">Главная</a></li>
                <li><span>Корзина</span></li>
            </ul>
        </div>

        <h1 class="page-title">Корзина</h1>

        {% if cart.count %}
            <div class="cart">
                <div class="cart-container">
                    <div class="cart-table">
                        <div class="cart-table-head">
                            <div class="cart-table-row">
                                <div class="cart-table-col cart-table-col_product">
                                    <span class="cart-table-head__title">Ваш заказ</span>
                                </div>
                                <div class="cart-table-col cart-table-col_price">
                                    <span class="cart-table-head__title">Цена</span>
                                </div>
                                <div class="cart-table-col cart-table-col_count">
                                    <span class="cart-table-head__title">Количество</span>
                                </div>
                                <div class="cart-table-col cart-table-col_total">
                                    <span class="cart-table-head__title">Сумма</span>
                                </div>
                                <div class="cart-table-col cart-table-col_delete"></div>
                            </div>
                        </div>
                        <div class="cart-table-body">
                            {% include "shop/includes/cart-items.html" %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-6 col-12">
                            <p class="cart-desc">После оформления заявки на сайте мы свяжемся с вами. Уточним цены на интересующие товары, рассчитаем сроки и стоимость доставки.</p>
                        </div>
                        <div class="col-xl-6 col-12">
                            <div class="cart-order">
                                {% count_cart as cart_total %}
                                <p class="cart-text">Итого: <span class="cart-total">{{ cart_total|format_number }}</span><span class="cart-currency">руб.</span></p>
                                <a class="cart-order-btn simple-button simple-button_inverse" href="{% url 'order' %}" onclick="ym(56972323, 'reachGoal', 'oform'); return true;">Оформить заказ</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
            {% include "./includes/cart-empty.html" %}
        {% endif %}
    </div>
</div>
{% endblock %}

apps/shop/templates/shop/order-mail.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <title>Ваш заказ №{{ order.id }}</title>
    </head>

    <body>

        <table
            border="0"
            cellpadding="0"
            cellspacing="0"
            style="margin:0; padding: 60px 20px"
            width="100%"
            bgcolor="#e7e7e7">
            <tr>
                <td align="center">

                    <div style="width: 560px; text-align: left; border: 1px solid #e0e0e0; background-color: #ffffff; margin: 0 auto;">
                         <div style="padding: 10px 30px 13px; border-bottom: 1px solid #e0e0e0; background-color: {{color}};">
                            <table style="width: 100%;">
                                <tr>
                                    <td>
                                        <img src="{{ request.scheme }}://{{ request.META.HTTP_HOST }}/static/images/header-logo.svg" alt="" border="0" style="display:block;" />
                                    </td>
                                    <td align="right" valign="middle">
                                        <a href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}/" target="_blank" style="font-family: Arial; font-weight: 700; font-size: 16px; color: #ffffff; text-decoration: none;">{{ request.META.HTTP_HOST }}</a>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="background-color: #f5f5f5; font-family: Arial; font-size: 15px; font-weight: 400; line-height: 20px; color: #1c1c1c; padding: 30px 30px 20px;">
                            <p style="font-size: 30px; line-height: normel; margin: 0 0 20px;">Ваш заказ №{{ order.id }}</b></p>
                            <p style="margin: 10px 0;">ФИО: <b> {{ order.surname }} {{ order.name }} {{ order.middle_name }} </b></p>
                            <p style="margin: 10px 0;">Email: <b>{{ order.email }}</b></p>
                            <p style="margin: 10px 0;">Телефон: <b>{{ order.phone }}</b></p>
                            <p style="margin: 10px 0;">Способ оплаты: <b>{{ order.str_type_payment }}</b></p>
                            {% if order.is_shipping_default %}
                                <p style="margin: 10px 0;">Способ получения: <b>{{ order.get_shipping_display }}</b></p>
                                <p style="margin: 10px 0;">Адрес магазина: <b>{{ order.shop_address }}</b></p>
                            {% else %}
                                <p style="margin: 10px 0;">Способ доставки: <b>{{ order.get_shipping_display }}</b></p>
                                <p style="margin: 10px 0;">Адрес доставки: <b>{{ order.get_shipping_address }}</b></p>
                            {% endif %}
                            {% if order.jurical and order.company_title %}
                            <p style="margin: 10px 0;">Название компании: <b>{{ order.company_title }}</b></p>
                            {% endif %}
                            {% if order.jurical and order.company_inn %}
                            <p style="margin: 10px 0;">ИНН компании: <b>{{ order.company_inn }}</b></p>
                            {% endif %}
                            {% if order.jurical and order.payment_file %}
                            <p style="margin: 10px 0;">Реквизиты: <b>
                                    <a href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}/{{ order.payment_file.url }}">{{ order.get_filename }}</a>
                                </b>
                            </p>
                            {% endif %}
                        </div>
                        {% if order.city %}
                        <div style="background-color: #f5f5f5; font-family: Arial; font-size: 15px; font-weight: 400; line-height: 20px; color: #1c1c1c; padding: 30px 30px 20px;">
                            <p style="font-size: 20px; line-height: normel; margin: 0 0 15px;">Адрес доставки</b></p>
                            <p style="margin: 10px 0;">Почтовый индекс: <b>{{ order.post_code }}</b></p>
                            <p style="margin: 10px 0;">Область: <b>{{ order.region }}</b></p>
                            <p style="margin: 10px 0;">Район: <b>{{ order.district }}</b></p>
                            <p style="margin: 10px 0;">Населенный пункт: <b>{{ order.city }}</b></p>
                            <p style="margin: 10px 0;">Улица: <b>{{ order.street }}</b></p>
                            <p style="margin: 10px 0;">Дом: <b>{{ order.house }}</b></p>
                            <p style="margin: 10px 0;">Корпус: <b>{{ order.housing }}</b></p>
                            <p style="margin: 10px 0;">Квартира: <b>{{ order.apartment }}</b></p>
                        </div>
                        {% endif %}

                        {% if order.comment %}
                            <p style="margin: 10px 0;">Ваш комментарий: <b>{{ order.comment }}</b></p>
                        {% endif %}


                        <div style="padding:15px 30px 0 30px;">
                            <table
                                border="0"
                                cellpadding="0"
                                cellspacing="0"
                                style="margin:0; table-layout: auto"
                                width="100%">

                                <tr height="25px" style="font-family: Arial; font-weight: 400; font-size: 13px; color: #1c1c1c; line-height: 20px;">
                                    <td align="left" colspan="2" style="border-bottom: 1px solid #e0e0e0;">Состав заказа</td>
                                    <td align="left" width="65" style="border-bottom: 1px solid #e0e0e0;">Кол-во</td>
                                    <td align="left" width="90" style="border-bottom: 1px solid #e0e0e0;">Сумма</td>
                                </tr>

                                {% for item in order.order_items.all %}
                                    <tr style="font-family: Arial; font-weight: 400; font-size: 15px; color: #1c1c1c; vertical-align: top;">
                                        <td width='75' style="border-bottom: 1px solid #e0e0e0; padding: 16px 0;">
                                            <div>
                                                {% if item.product.thumbnail %}
                                                    <img src="{{ request.scheme}}://komsis.su/{{ item.product.thumbnail.url }}" alt="" border="0" width="60" height="60" style="display:block; margin: 0; object-fit: contain;" />
                                                {% else %}
                                                    <img src="{{ request.scheme}}://komsis.su/static/images/no-photo.png" alt="" border="0" width="60" height="60" style="display:block; margin: 0;" />
                                                {% endif %}
                                            </div>
                                        </td>
                                        <td width="270" style="border-bottom: 1px solid #e0e0e0; padding: 16px 0;">
                                            <div style="padding-top: 5px;">
                                                {% if item.option %}
                                                    {% if item.option.product.code %}<p style="font-size: 13px; margin: 0;">Арт.{{ item.option.product.code }}</p>{% endif %}
                                                    <p style="font-size: 13px; margin: 0;">{{ item.product.title }} {{ item.option.title }}</p>
                                                    {% comment %}
                                                    <p style="font-weight: 700; margin: 0;">{{ item.option.price }} руб.</p>
                                                    {% endcomment %}
                                                {% else %}
                                                    {% if item.product.code %}<p style="font-size: 13px; margin: 0;">Арт.{{ item.product.code }}</p>{% endif %}
                                                    <p style="font-size: 13px; margin: 0;">{{ item.product.title }}</p>
                                                    {% comment %}
                                                    <p style="font-weight: 700; margin: 0;">{{ item.product.price }} руб.</p>
                                                    {% endcomment %}
                                                {% endif %}
												<p style="font-weight: 700; margin: 0;">{{ item.total }} руб.</p>
                                            </div>
                                        </td>
                                        <td style="border-bottom: 1px solid #e0e0e0; padding: 16px 0;">
                                            <div style="padding-top: 13px;">
                                                <p style="margin: 0;">{{ item.count }} {{ item.product.unit }}.</p>
                                            </div>
                                        </td>
                                        <td style="border-bottom: 1px solid #e0e0e0; padding: 16px 0;">
                                            <div style="padding-top: 16px;">
                                                <p style="font-weight: 700; margin: 0;">{{ item.total_price }} руб.</p>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </table>
                            <table style="width: 100%; font-family: Arial; font-weight: 400; font-size: 24px; color: #1c1c1c; padding: 20px 0 25px;">
                                <tr>
                                    <td align="left" style="padding: 0;"><p style="margin: 0;"><b>Итого к оплате:</b></p></td>
                                    <td align="right" style="padding: 0;"><p style="margin: 0;"><b>{{ order.total|floatformat:2 }} руб.</b></p></td>
                                </tr>
                            </table>
                        </div>
                    </div>

                </td>
            </tr>
        </table>
    </body>

</html>