apps/account/urls.py
from django.contrib.auth.views import (PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from .views import (ChangeDataView, ChangePasswordView, CreateAccountView,
                    CustomPasswordResetConfirmView,
                    CustomPasswordResetDoneView, CustomPasswordResetView,
                    DataTemplate, FavoritesTemplate, FavoritesWaitingList,
                    JuricalOrdersList, LoginView, LogoutView, OrderDeleteView,
                    OrderDetail, OrderItemDeleteView, OrdersList,
                    OrderToPdfView, OrderUpdateView, PasswordTemplate,
                    RegisterView, SubscribeAddView, SubscribeTemplate)

app_name = "accounts"
urlpatterns = [
    path(
        'account/register/',
        CreateAccountView.as_view(),
        name='account-create'
    ),
    path('account/orders/', OrdersList.as_view(), name='account-orders'),
    path('account/orders/jurical/', JuricalOrdersList.as_view(),
         name='account-orders-jurical'),
    path('account/orders/<int:pk>/',
         OrderDetail.as_view(), name='account-order'),
    path('account/data/', DataTemplate.as_view(), name='account-data'),
    path('account/favorites/', FavoritesTemplate.as_view(),
         name='account-favorites'),
    path('account/waiting/', FavoritesWaitingList.as_view(),
         name='account-waiting'),
    path('account/password/', PasswordTemplate.as_view(),
         name='account-password'),
    path('account/subscribe/', SubscribeTemplate.as_view(),
         name='account-subscribe'),

    # Ajax обработчики

    path('api/account/login/', LoginView.as_view(),
         name='account-login'),
    path('api/account/orders/<int:pk>/remove/', OrderDeleteView.as_view(),
         name='order-delete'),
    path('api/account/orders/<int:pk>/update/', OrderUpdateView.as_view(),
         name='order-update'),
    path('api/account/orders/<int:pk>/item/remove/', OrderItemDeleteView.as_view(),
         name='order-item-delete'),
    path('api/account/orders/<int:pk>/pdf/', OrderToPdfView.as_view(),
         name='order-to-pdf'),
    path('api/account/register/', RegisterView.as_view(),
         name='account-register'),
    path('api/account/logout/', LogoutView.as_view(),
         name='account-logout'),
    path('api/account/data/change/', ChangeDataView.as_view(),
         name='account-change-data'),
    path('pi/account/subscribe/add/', SubscribeAddView.as_view(),
         name='account-subscribe-add'),
    path('api/account/password/change/', ChangePasswordView.as_view(),
         name='account-change-password'),

    path(
        'user/password/reset/',
        CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        'user/password/reset/done/',
        CustomPasswordResetDoneView.as_view(), name="password_reset_done"
    ),
    path(
        'user/password/reset/<slug:uidb64>/<slug:token>/',
        CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),

    path('user/password/done/',
         PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

apps/shop/urls.py
from django.urls import path

from .views import (AddCompareView, AddFavoritesView, AddWaitingFavoritesView,
                    AvailableView, CalculateShippingView, CartAddView,
                    CartDeleteView, CartTemplate, CartUpdateView, CompareView,
                    DeleteCompareView, DeleteFavoritesView, FavoritesView,
                    OrderCreate, OrderView, PaymentRedirectView,
                    RestoreCompareView, RestoreFavoritesView)

urlpatterns = [
    path('shop/cart/', CartTemplate.as_view(), name='cart'),
    path('shop/order/', OrderView.as_view(), name='order'),
    path('shop/favorites/', FavoritesView.as_view(), name='favorites'),
    path('shop/compare/', CompareView.as_view(), name='compare'),
    path('shop/validate-payment/',
         PaymentRedirectView.as_view(), name='validate-payment'),

    # Ajax обработчики

    path('api/shop/cart/available/', AvailableView.as_view(), name='available'),
    path('api/shop/order/calculate/',
         CalculateShippingView.as_view(), name='calculate-shipping'),
    path('api/shop/cart/add/', CartAddView.as_view(), name='cart-add'),
    path('api/shop/cart/update/', CartUpdateView.as_view(),
         name='cart-update'),
    path('api/shop/cart/delete/', CartDeleteView.as_view(),
         name='cart-delete'),
    path('api/shop/order/create/', OrderCreate.as_view(),
         name='order-create'),
    path('api/shop/favorites/add', AddFavoritesView.as_view(),
         name='favorites-add'),
    path('api/shop/favorites/delete', DeleteFavoritesView.as_view(),
         name='favorites-delete'),
    path('api/shop/favorites/restore', RestoreFavoritesView.as_view(),
         name='favorites-restore'),
    path('api/shop/favorites/add-waiting',
         AddWaitingFavoritesView.as_view(),
         name='favorites-add-waiting'),
    path('api/shop/compare/add', AddCompareView.as_view(),
         name='compare-add'),
    path('api/shop/compare/delete', DeleteCompareView.as_view(),
         name='compare-delete'),
    path('api/shop/compare/restore', RestoreCompareView.as_view(),
         name='compare-restore'),
]

system/urls.py
from apps.catalog.models import CategorySitemap, ProductSitemap
from apps.pages.views import return_js
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import Sitemap
from django.contrib.sitemaps.views import sitemap
#
from django.urls import include, path, reverse
#  delete later
from django.views.generic import RedirectView, TemplateView


class StaticViewSitemap(Sitemap):
    priority = 0.5
    changefreq = 'daily'

    def items(self):
        return ['catalog', ]

    def location(self, item):
        return reverse(item)


sitemaps = {
    'products': ProductSitemap,
    'categorys': CategorySitemap,
    # 'posts': SitemapCatPage,
    # 'catsposts': SitemapPost,
    # 'pages': SitemapPage,
    'static': StaticViewSitemap
}

urlpatterns = [
    path('favicon.ico',
         RedirectView.as_view(url='/static/images/favicon.png'),
         name='favicon'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    path('admin/', admin.site.urls),

    # Прочие приложения
    path('filer/', include('filer.urls')),
    path('ajax_lookup/', include('ajax_select.urls'),
         name='ajax_lookup'),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # delete later
    path('dev_page', TemplateView.as_view(
        template_name="dev_page.html"), name='dev_page'),
    path('dev_text_page', TemplateView.as_view(
        template_name="dev_text_page.html"), name='dev_page'),
    # path('404', not_found_view),

    path('sw.js', return_js),

    # Основные приложения
    path('', include('apps.seo.urls')),
    path('', include('apps.feedback.urls')),
    path('', include('apps.exchange1c.urls')),
    path('', include('apps.catalog.urls')),
    path('', include('apps.account.urls')),
    path('', include('apps.shop.urls')),
    path('', include('apps.pages.urls')),
    path('', include('apps.posts.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/shop/views/cart.py
import json
import re

from apps.catalog.models import Color, Option, Product
from django.http import JsonResponse
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.utils.encoding import repercent_broken_unicode
from django.views.generic import TemplateView, View

from ..models import Cart, CartItem, UnauthCart, UnauthCartItem


class CartTemplate(TemplateView):
    template_name = 'shop/cart.html'


class CartAddView(View):
    """
    Обработчик добавления товаров и опций в корзину.
    """

    def post(self, request):
        post_data = request.POST
        product = Product.objects.get(id=int(post_data['product-id']))
        count = int(post_data.get('product-count', 1))
        colors = product.colors.all()

        try:
            color = Color.objects.get(id=int(post_data['product-color']))
        except KeyError:
            color = None
            if colors:
                return JsonResponse({
                    'errors': True, 'message': 'Выберите цвет'})

        try:
            option = Option.objects.get(id=int(post_data['product-option']))
        except KeyError:
            option = None
            if option:
                return JsonResponse({
                    'errors': True, 'message': 'Выберите опцию'})

        if post_data.get('products', False):
            products = json.loads(post_data['products'])
            for item in products:
                option = Option.objects.get(id=int(item['option']))
                if request.user.is_authenticated:
                    cart = self.create_auth_cart(
                        request, product, color, option, int(item["count"]))
                else:
                    cart = self.create_unauth_cart(
                        request, product, color, option, int(item["count"]))
            return JsonResponse({
                'count': cart.count(),
                'dropdown': render_dropdown(cart, request),
                'ecommerce-product': {"id": str(product.id), "name": str(product.title), "price": str(option.price),
                                      "category": str(product.category.title),
                                      "quantity": count}
            })

        if request.user.is_authenticated:
            cart = self.create_auth_cart(
                request, product, color, option, count)
        else:
            cart = self.create_unauth_cart(
                request, product, color, option, count)
        p = product
        return JsonResponse({
            'count': cart.count(),
            'dropdown': render_dropdown(cart, request),
            'ecommerce-product': {"id": str(p.id), "name": str(p.title), "price": str(p.price),
                                  "category": str(p.category.title), "quantity": count}
        })

    def create_auth_cart(self, request, product, color, option, count):
        """Создание корзины товаров авторизованного пользователя.

        Arguments:
            request {DjangoRequest} -- Запрос на сервер
            product {Product} -- Экземпляр товара
            color {Color} -- Экземпляр опции цвета товара
            count {int} -- Количество товаров

        Returns:
            Cart -- Корзина товаров
        """

        cart = Cart.objects.get(account__user=request.user)
        account = request.user.account
        fields = {'count': count}
        cart_item, created = CartItem.objects.select_related("product").get_or_create(
            cart=cart, product=product, color=color, option=option, defaults=fields)
        if not created:
            if (count + cart_item.count) >= cart_item.product.count:
                if product.is_able_to_overflow_count:
                    # Добавляем возможность каждому пользователю
                    # заказывать товары сверх остатка
                    cart_item.count = count
                else:
                    cart_item.count = cart_item.product.count
            else:
                cart_item.count += count
            cart_item.save()
        return cart

    def create_unauth_cart(self, request, product, color, option, count):
        """Создание корзины товаров неавторизованного пользователя.

        Arguments:
            request {DjangoRequest} -- Запрос на сервер
            product {Product} -- Экземпляр товара
            color {Color} -- Экземпляр опции цвета товара
            count {int} -- Количество товаров

        Returns:
            UnauthCart -- Корзина товаров
        """

        cart = request.session.get('cart', None)
        if cart:
            if cart.count():
                found_item = False
                for key, item in enumerate(cart.cart_items):
                    if item.product == product and item.color == color and item.option == option:
                        # Если был найден переданный товар
                        found_item = True
                        if (item.count + count) >= item.product.count:
                            # если кол-во товаров в корзине будет первышать
                            # остаток товаров на складе
                            if product.is_able_to_overflow_count:
                                # если у товара есть возможность превышать остаток
                                cart.cart_items[key].count = count
                            else:
                                # если нет, просто делаем кол-во товара в корзине равным
                                # остатку товара
                                cart.cart_items[key].count = item.product.count
                        else:
                            cart.cart_items[key].count = item.count + count
                if not found_item:
                    cart.add(UnauthCartItem(
                        product=product, color=color, option=option, count=count))
            else:
                cart.cart_items = [UnauthCartItem(
                    product=product, color=color, option=option, count=count)]
        else:
            cart = UnauthCart(cart_items=[UnauthCartItem(
                product=product, color=color, option=option, count=count)])
        request.session['cart'] = cart
        request.session.save()
        return cart


class CartUpdateView(View):
    """Обработчик обновление количества товаров и их суммы в корзине.

    Arguments:
        View {object} -- Базовый класс представлений Django.

    Returns:
        dict -- Возвращаяет данные корзины в виде json.
    """

    def post(self, request):
        post_data = request.POST
        count = int(post_data['product-count'])

        product = Product.objects.get(id=post_data['product-id'])
        try:
            color = Color.objects.get(id=int(post_data['product-color']))
        except KeyError:
            color = None
        try:
            option = Option.objects.get(id=int(post_data['product-option']))
        except KeyError:
            option = None
        if request.user.is_authenticated:
            cart, cart_item = self.update_auth_cart_item(
                request, product, color, option, count)
        else:
            cart, cart_item = self.update_unauth_cart_item(
                request, product, color, option, count)
        p = product
        user = request.user
        account = user.account if user.is_authenticated else None
        response_price = cart_item.count_total_by_account(account)
        response_total = cart.count_total_by_account(account)
        is_overflowed = cart_item.is_count_overflowed
        json_response = {
            'product_id': cart_item.product.id if not cart_item.option else cart_item.option.id,
            'item_count': cart_item.count,
            'count': cart.count(),
            'price': round(response_price, 2),
            'total': round(response_total, 2),
            'is_overflowed': is_overflowed,
            'dropdown': render_dropdown(cart, request),
            'ecommerce-product': {"id": str(p.id), "name": str(p.title),
                                  "price": str(option.price) if option else str(p.price),
                                  "category": str(p.category.title), "quantity": str(count)}
        }
        return JsonResponse(json_response)

    def update_auth_cart_item(self, request, product, color, option, count):
        """Обновление элемента в корзине авторизованного пользователя.

        Arguments:
            request {object} -- Запрос на сервер
            product {Product} -- Товар
            color {Color} -- Опция цвета
            count {int} -- Количесто товаров

        Returns:
            (Cart, CartItem) -- Корзина товаров и измененный
            элемент корзины
        """

        cart = Cart.objects.filter(account__user=request.user).first()
        cart_item = CartItem.objects.get(
            cart=cart, product=product, color=color, option=option)

        account = request.user.account
        if count > cart_item.product.get_total_count():
            if product.is_able_to_overflow_count:
                cart_item.count = count
            else:
                cart_item.count = cart_item.product.get_total_count()
        else:
            cart_item.count = count
        cart_item.save()
        return cart, cart_item

    def update_unauth_cart_item(self, request, product, color, option, count):
        """Обновление элемента в корзине неавторизованного пользователя.

        Arguments:
            request {object} -- Запрос на сервер
            product {Product} -- Товар
            color {Color} -- Опция цвета
            count {int} -- Количесто товаров

        Returns:
            (UnauthCart, UnauthCartItem) -- Корзина товаров и измененный
            элемент корзины
        """

        cart = request.session['cart']
        for key, item in enumerate(cart.cart_items):
            if item.product == product and item.color == color and item.option == option:
                if count > cart.cart_items[key].product.count:

apps/shop/templates/shop/includes/account-dropdown.html
<div class="shop-dropdown shop-dropdown_theme_account account-dropdown">
    <div class="shop-dropdown__head">
        {% if account %}
            <p class="shop-dropdown__title">{{ account }}</p>
        {% else %}
            <p class="shop-dropdown__title">Личный кабинет</p>
        {% endif %}
        <svg class="shop-dropdown__icon" role="img"><use xlink:href="/static/images/sprite.svg#user"></use></svg>
    </div>
    <div class="shop-dropdown__body shop-dropdown__body_list">
        <ul class="dropdown-list">
            {% if account %}
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="{% url 'accounts:account-orders' %}">Мои заказы</a>
                </li>
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="{% url 'accounts:account-data' %}">Личные данные</a>
                </li>
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="{% url 'accounts:account-password' %}">Изменить пароль</a>
                </li>
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="{% url 'accounts:account-favorites' %}">Избранные товары</a>
                </li>
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="{% url 'accounts:account-waiting' %}">Лист ожидания</a>
                </li>
                {% comment %}
                    <li class="dropdown-list__item">
                        <a class="dropdown-list__link" href="{% url 'account-orders' %}">Бонусный счет</a>
                    </li>
                {% endcomment %}
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="{% url 'account-subscribe' %}">Управление подписками</a>
                </li>
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link dropdown-list__link_theme_exit" href="">
                        <span>Выход</span><svg class="dropdown-list__icon" role="img"><use xlink:href="/static/images/sprite.svg#exit"></use></svg>
                    </a>
                </li>
            {% else %}
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link modal_trigger" href="#custom_modal-1">Войти</a>
                </li>
                <li class="dropdown-list__item">
                    <a class="dropdown-list__link" href="">Регистрация</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

apps/shop/templates/shop/includes/auth_order_form.html
<div class="checkout-form__form-part-body">
    <div class="order-error" style='display:none;color:red;'></div>
    <div class="form-group ">
        <span for="name" class='title'>ФИО</span>
        <span>{{ account.surname }} {{ account.name }} {{ account.middle_name }}</span>
        <input name="name" class="form-control" type="hidden" id="name" value="{{ account.name }}" required="required"/>
        <input name="surname" class="form-control" type="hidden" id="surname" value="{{ account.surname }}" required="required"/>
        <input name="middle_name" class="form-control" type="hidden" id="middle_name" value="{{ account.middle_name }}"/>
        <div class="valid-feedback">Готово!</div>
    </div>
    <div class="form-group ">
        <span for="email" class='title'>Email</span>
        <span>{{ account.email }}</span>
        <input name="email" class="form-control" type="hidden" id="email" value="{{ account.email }}" required="required"/>
        <div class="invalid-feedback">Обязательное поле для заполнение</div>
    </div>
    <div class="form-group ">
        <span for="user_phone" class='title'>Телефон</span>
        <span>{{ account.phone }}</span>
        <input name="phone" class="form-control" type="hidden" id="user_phone" value="{{ account.phone }}" required="required"/>
        <div class="invalid-feedback">Обязательное поле для заполнение</div>
    </div>
    {% if account.jurical %}
        <div class="form-group custom_checkbox">
            <div class="custom-control custom-checkbox">
                {% if not saved_order %}
                    <input class="custom-control-input" type="checkbox" id="face" name="face" {% if account.jurical %}checked{% endif %}>
                {% elif saved_order.jurical %}
                    <input class="custom-control-input" type="checkbox" id="face" name="face" checked>
                {% elif not saved_order.jurical %}
                    <input class="custom-control-input" type="checkbox" id="face" name="face">
                {% endif %}
                <label class="custom-control-label title" for="face">Заказ от юридического лица</label>
                <div class="invalid-feedback"></div>
            </div>
            <div class="face_step"  style="display: {% if account.jurical %}block{% else %}none{% endif %};">
                <div class="form-group ">
                    <span for="company" class='title'>Название компании</span>
                    <span>{{ account.company_title }}</span>
                    <input name="company_title" class="form-control" type="hidden" id="company" value="{{ account.company_title }}"/>
                    <div class="invalid-feedback">Обязательное поле для заполнение</div>
                </div>
                <div class="row__container">
                    <div class="form-group ">
                        <span for="inn" class='title'>ИНН</span>
                        <span>{{ account.company_inn }}</span>
                        <input name="company_inn" class="form-control" type="hidden" id="inn" value="{{ account.company_inn }}"/>
                        <div class="invalid-feedback">Обязательное поле для заполнение</div>
                    </div>
                    <div class="example-1">
                    <div class="form-group">
                        <label class="label">
                            <svg id="Capa_1" enable-background="new 0 0 512 512" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg">
                                <path d="m226 512c-49.626 0-90-40.374-90-90v-302c0-66.168 53.832-120 120-120s120 53.832 120 120v302h-30v-302c0-49.626-40.374-90-90-90s-90 40.374-90 90v302c0 33.084 26.916 60 60 60s60-26.916 60-60v-242c0-16.542-13.458-30-30-30s-30 13.458-30 30v242h-30v-242c0-33.084 26.916-60 60-60s60 26.916 60 60v242c0 49.626-40.374 90-90 90z"/>
                            </svg>
                            <input type="file" name="file-payment">
                            <span class="title">Добавить файл</span>
                        </lable>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <input class="custom-control-input" type="hidden" id="hidden_jurical_checkbox" value="false">
    {% endif %}
    <div class="form-group">
        <span class="">Ваш комментарий к заказу </span>
        <textarea name="comment" id="comment" cols="30" rows="10"></textarea>
        <div class="invalid-feedback">Ваш комментарий слишком большой!</div>
    </div>
</div>

apps/shop/templates/shop/includes/cart-dropdown.html
{% load utils %}

{% if cart.count %}
    <div class="order-table">
        <div class="order-table__header">
            <div class="order-table__row">
                <div class="info">Ваш заказ</div>
                <div class="price">Цена</div>
                <div class="amount">Количество</div>
                <div class="total-price">Сумма</div>
                <div class="delete-item"></div>
            </div>
        </div>
        <div class="order-table__body">
                {% include "shop/includes/cart-items.html" with request=request %}
        </div>
        <div class="order-table__total">Итого: 
            {% count_cart as cart_total %}
            <b>{{ cart_total }} руб.</b>
        </div>
    </div>
{% endif %}

apps/shop/templates/shop/includes/cart-empty.html
<div class="notify">
    <div class="notify-body">
        <svg class="notify-icon" role="img">
            <use xlink:href="/static/images/sprite.svg#cart"></use>
        </svg>
        <div class="notify-text">
            <p class="notify-title">Ваша корзина пуста</p>
            <p class="notify-desc">Для добавления товаров в корзину перейдите в каталог</p>
        </div>
    </div>
    <a class="notify-button btn btn-primary" href="{% url 'catalog' %}">Перейти в каталог</a>
</div>

apps/shop/templates/shop/includes/compare-restore.html
<div class="favorites-restore">
    <button class="favorites-restore__button" data-product="{{ product.id }}" data-action="{% url 'compare-restore' %}" type="button">
        <svg class="favorites-restore__icon" role="img"><use xlink:href="/static/images/sprite.svg#back"></use></svg>
    </button>
</div>

apps/shop/templates/shop/includes/favorites-restore.html
<div class="favorites-restore">
    <button class="favorites-restore__button" data-product="{{ product.id }}" data-action="{% url 'favorites-restore' %}" type="button">
        <svg class="favorites-restore__icon" role="img"><use xlink:href="/static/images/sprite.svg#back"></use></svg>
    </button>
</div>

apps/shop/templates/shop/includes/order-success.html
<div class="col-12">
<div class="notification_block">
    <div class="wrapper_left">
        <div class="icon_wrapper">
            <svg role="img" width="57" height="57"><use xlink:href="/static/images/sprite.svg#done_icon"></use></svg>
        </div>
        <div class="text">
            <b>Заказ №{{ order.id }} успешно {% if not order.is_in_stash %}оформлен{% else %}сохранен{% endif %}</b>
            {% if not order.is_in_stash %}
                <span>Ожидайте звонка менеджера для подтверждения заказа</span>
            {% else %}
                <span>Вы всегда можете перейти в личный кабинет и продолжить оформление заказа</span>
            {% endif %}
        </div>
    </div>
</div>
</div>

apps/shop/templates/shop/includes/unauth_order_form.html
<div class="checkout-form__form-part-body">

    <div class="form-group required">
        <label for="surname">Фамилия</label>
        <input name="surname" class="form-control" type="text" id="surname" value="{{ request.user.account.surname }}" required="required"/>
        <div class="valid-feedback">Готово!</div>
    </div>
    <div class="form-group required">
        <label for="name">Имя</label>
        <input name="name" class="form-control" type="text" id="name" value="{{ request.user.account.name }}" required="required"/>
        <div class="valid-feedback">Готово!</div>
    </div>
    <div class="form-group ">
        <label for="middle_name">Отчество</label>
        <input name="middle_name" class="form-control" type="text" id="middle_name" value="{{ request.user.account.middle_name }}"/>
        <div class="valid-feedback">Готово!</div>
    </div>

    <div class="form-group required">
        <label for="email">Email</label>
        <input name="email" class="form-control" type="email" id="email" value="{{ request.user.account.email }}" required="required"/>
        <div class="invalid-feedback">Обязательное поле для заполнение</div>
    </div>
    <div class="form-group required">
        <label for="user_phone">Телефон</label>
        <input name="phone" class="form-control" type="tel" id="user_phone" value="{{ request.user.account.phone }}" required="required"/>
        <div class="invalid-feedback">Обязательное поле для заполнение</div>
    </div>
    <div class="form-group custom_checkbox">
         <div class="custom-control custom-checkbox">
            <input class="custom-control-input" type="checkbox" id="face" name="face" >
            <label class="custom-control-label" for="face">Я являюсь юридическим лицом</label>
            <div class="invalid-feedback"></div>
        </div>
        <div class="face_step" style="display: none;">
            <div class="form-group required">
                <label for="company">Название компании</label>
                <input name="company_title" class="form-control" type="text" id="company" value="{{ request.user.account.company_title }}"/>
                <div class="invalid-feedback">Обязательное поле для заполнение</div>
            </div>
            <div class="row__container">
                <div class="form-group required">
                    <label for="inn">ИНН</label>
                    <input name="company_inn" class="form-control" type="number" id="inn" value="{{ request.user.account.company_inn }}"/>
                    <div class="invalid-feedback">Обязательное поле для заполнение</div>
                </div>
                <div class="example-1">
                  <div class="form-group">
                    <label class="label">
                        <svg id="Capa_1" enable-background="new 0 0 512 512" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg">
                            <path d="m226 512c-49.626 0-90-40.374-90-90v-302c0-66.168 53.832-120 120-120s120 53.832 120 120v302h-30v-302c0-49.626-40.374-90-90-90s-90 40.374-90 90v302c0 33.084 26.916 60 60 60s60-26.916 60-60v-242c0-16.542-13.458-30-30-30s-30 13.458-30 30v242h-30v-242c0-33.084 26.916-60 60-60s60 26.916 60 60v242c0 49.626-40.374 90-90 90z"/>
                        </svg>
                      <input type="file" name="file-payment">
                      <span class="title">Добавить файл</span>
                    </label>
                  </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <span class="">Ваш комментарий к заказу </span>
            <textarea name="comment" id="comment" cols="30" rows="10"></textarea>
            <div class="invalid-feedback">Ваш комментарий слишком большой</div>
        </div>
    </div>
</div>